export const sample_foods = [
  {
    id: '1',
    name: 'Gotukola',
    deleveryTime: '10-20',
    price: 150,
    favorite: false,
    origins: ['Kandy'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['Vegetable', 'Green',],
  },
  {
    id: '2',
    name: 'Melon',
    price: 200,
    deleveryTime: '20-30',
    favorite: true,
    origins: ['jaffna', 'kurunegala', 'dambulla'],
    stars: 300,
    imageUrl: 'food-2.jpg',
    tags: ['Fruit', 'Sweet'],
  },
  {
    id: '3',
    name: 'Guawa',
    price: 250,
    deleveryTime: '10-15',
    favorite: false,
    origins: ['anuradhapura', 'dambulla'],
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['Fruit', 'Sweet'],
  },
  {
    id: '4',
    name: 'Mango',
    price: 800,
    deleveryTime: '15-20',
    favorite: true,
    origins: ['dambulla',],
    stars: 3,
    imageUrl: 'food-4.jpg',
    tags: ['Fruit', 'Sweet'],
  },
  {
    id: '5',
    name: 'Grapes',
    price: 600,
    cookTime: '40-50',
    favorite: false,
    origins: ['jaffna'],
    stars: 3.5,
    imageUrl: 'food-5.png',
    tags: ['Fruit','Sweet','Green'],
  },
  {
    id: '6',
    name: 'Brocolli',
    price: 450,
    deleveryTime: '40-50',
    favorite: false,
    origins: ['kandy'],
    stars: 4.0,
    imageUrl: 'food-6.jpg',
    tags: ['Vegetable', 'Green'],
  },
  {
    id: '7',
    name: 'Cucumber',
    price: 180,
    deleveryTime: '40-50',
    favorite: false,
    origins: ['kurunegala','anuradhapura'],
    stars: 4.0,
    imageUrl: 'food-7.jpg',
    tags: ['Vegetable'],
  },
  {
    id: '8',
    name: 'Pepper',
    price: 1000,
    deleveryTime: '40-50',
    favorite: false,
    origins: ['kurunegala'],
    stars: 4.0,
    imageUrl: 'food-8.jpg',
    tags: ['Vegetable', 'Spicy'],
  },

];

export const sample_tags = [
  { name: 'All', count: 8 },
  { name: 'Vegetable', count: 4 },
  { name: 'Green', count: 3 },
  { name: 'Fruit', count: 4 },
  { name: 'Sweet', count: 4 },
  { name: 'Spicy', count: 1 },
];
